"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' 

[directory]
truncation_symbol = '…/'

