"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' 

[directory]
truncation_symbol = '…/'

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
untracked = '?${count}'
stashed = '$${count}'
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[container]
disabled = true

[custom.foo]
command = 'echo $SHPOOL_SESSION_NAME' # shows output of command
when = '[ -n "$SHPOOL_SESSION_NAME" ] && exit 0 || exit 1'
style = 'bold blue'
format = '[\[shpool: $output\]]($style)'
