return {
	-- leap.nvim
	-- {
	-- 	"ggandor/leap.nvim",
	-- 	config = function()
	-- 		require('leap').add_default_mappings()
	-- 	end
	-- },
	-- {
	-- 	"ggandor/flit.nvim",
	-- 	dependencies = {
	-- 		"ggandor/leap.nvim",
	-- 	},
	-- 	config = function()
	-- 		require('flit').setup {
	-- 			labeled_modes = "nv",
	-- 		}
	-- 	end
	-- },
	-- {
	-- 	"ggandor/leap-ast.nvim",
	-- 	dependencies = {
	-- 		"ggandor/leap.nvim",
	-- 	},
	-- 	config = function()
	-- 		vim.keymap.set({'n', 'x', 'o'}, '<C-s>', function() require'leap-ast'.leap() end, {})
	-- 	end
	-- },
	-- {
	-- 	"ggandor/leap-spooky.nvim",
	-- 	dependencies = {
	-- 		"ggandor/leap.nvim",
	-- 	},
	-- 	config = function()
	-- 		require('leap-spooky').setup {}
	-- 	end
	-- },
}
